# Generated by Django 4.0.5 on 2022-06-02 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseName', models.CharField(blank=True, max_length=100, null=True)),
                ('ownerName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=50)),
                ('rent', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('allowed', models.CharField(choices=[('all', 'All'), ('couple', 'Couple'), ('bachelor(male)', 'Bachelor(Male)'), ('bachelor(female)', 'Bachelor(Female)'), ('family', 'Family')], default='all', max_length=50)),
                ('roomType', models.CharField(choices=[('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK'), ('4bhk', '4BHK'), ('single room', 'Single Room'), ('double room', 'Double Room'), ('whole house', 'Whole House')], default='single room', max_length=25)),
                ('building_img', models.ImageField(upload_to='images/')),
                ('bedroom_img', models.ImageField(upload_to='images/')),
                ('kitchen_img', models.ImageField(upload_to='images/')),
                ('bathroom_img', models.ImageField(upload_to='images/')),
                ('favorite', models.ManyToManyField(related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='HouseRentalApp.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
