# Generated by Django 4.0.5 on 2022-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRentalApp', '0002_alter_house_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
